name: tests

on: ['push', 'pull_request']

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, windows-2019]
        php: [8.2, 8.3, 8.4]
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: |
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute lint tests
        run: vendor/bin/php-cs-fixer check
        if: matrix.php != '8.4'

      - name: Execute static analysis
        run: vendor/bin/phpstan
        if: matrix.php == '8.2'

      - name: Execute unit/feature tests
        run: vendor/bin/phpunit
